import SmoothingCliff.Mechanism.GeneralStability
import Mathlib.Probability.Distributions.Exponential

/-!
# The finite exponential-race representation of conditional stability

This file connects the conditional order-statistic model used by
`GeneralStability.lean` to a finite list of opponent exponential-race arrival
keys.  For fixed opponent keys, the only remaining randomness is the bidder's
own unit-rate exponential clock.  The rank events below are therefore genuine
interval events for that clock, and their probabilities are computed rather
than assumed.
-/

namespace SmoothingCliff.Mechanism

open MeasureTheory ProbabilityTheory
open scoped BigOperators

namespace ConditionedOpponentOrderStats

/-- Package a sorted finite list of nonnegative opponent arrival keys as the
order-statistic object used by the conditional stability calculation. -/
noncomputable def ofSortedList
    (arrival : List ℝ)
    (hNonnegative : ∀ t ∈ arrival, 0 ≤ t)
    (hSorted : arrival.SortedLE) :
    ConditionedOpponentOrderStats where
  threshold p :=
    if hp : p < arrival.length then some arrival[p] else none
  nonnegative := by
    intro p t ht
    split at ht
    next hp =>
      simp only [Option.some.injEq] at ht
      subst t
      exact hNonnegative arrival[p] (List.getElem_mem hp)
    next hp =>
      simp at ht
  ordered := by
    intro p t u ht hu
    split at ht
    next hp =>
      simp only [Option.some.injEq] at ht
      split at hu
      next hnext =>
        simp only [Option.some.injEq] at hu
        subst t
        subst u
        exact hSorted.getElem_le_getElem_of_le (Nat.le_succ p)
      next hnext =>
        simp at hu
    next hp =>
      simp at ht
  padding := by
    intro p hp
    by_cases hlt : p < arrival.length
    · simp [hlt] at hp
    · have hsucc : ¬ p + 1 < arrival.length := by omega
      simp [hsucc]
  finite := by
    refine ⟨arrival.length, ?_⟩
    simp

theorem ofSortedList_threshold
    (arrival : List ℝ)
    (hNonnegative : ∀ t ∈ arrival, 0 ≤ t)
    (hSorted : arrival.SortedLE) (p : ℕ) :
    (ofSortedList arrival hNonnegative hSorted).threshold p =
      if hp : p < arrival.length then some arrival[p] else none := by
  rfl

end ConditionedOpponentOrderStats

/-- The sorted multiset of all arrival keys except the distinguished bidder. -/
noncomputable def sortedOpponentKeys
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (key : ι → ℝ) (i : ι) : List ℝ :=
  ((Finset.univ.erase i).val.map key).sort (· ≤ ·)

theorem sortedOpponentKeys_sorted
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (key : ι → ℝ) (i : ι) :
    (sortedOpponentKeys key i).SortedLE := by
  unfold sortedOpponentKeys
  apply List.sortedLE_iff_pairwise.mpr
  exact Multiset.pairwise_sort _ (fun x y : ℝ => x ≤ y)

theorem sortedOpponentKeys_nonnegative
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (key : ι → ℝ) (i : ι)
    (hKey : ∀ j, j ≠ i → 0 ≤ key j) :
    ∀ t ∈ sortedOpponentKeys key i, 0 ≤ t := by
  intro t ht
  rw [sortedOpponentKeys, Multiset.mem_sort] at ht
  rcases Multiset.mem_map.mp ht with ⟨j, hj, rfl⟩
  apply hKey j
  have hj' : j ∈ Finset.univ.erase i := hj
  exact (Finset.mem_erase.mp hj').1

theorem sortedOpponentKeys_length
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (key : ι → ℝ) (i : ι) :
    (sortedOpponentKeys key i).length = Fintype.card ι - 1 := by
  rw [sortedOpponentKeys, Multiset.length_sort, Multiset.card_map]
  change (Finset.univ.erase i).card = Fintype.card ι - 1
  rw [Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ]

/-- Push a finite opponent key vector through sorting into the conditional
order-statistic representation. -/
noncomputable def opponentOrderStats
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (key : ι → ℝ) (i : ι)
    (hKey : ∀ j, j ≠ i → 0 ≤ key j) :
    ConditionedOpponentOrderStats :=
  ConditionedOpponentOrderStats.ofSortedList
    (sortedOpponentKeys key i)
    (sortedOpponentKeys_nonnegative key i hKey)
    (sortedOpponentKeys_sorted key i)

/-- The concrete order statistics generated by the opponents' Plackett--Luce
exponential-race keys. -/
noncomputable def plOpponentOrderStats
    {Ω ι : Type*} [Fintype ι] [DecidableEq ι]
    (reserve temperature : ℝ) (shock : Ω → ι → ℝ)
    (bids : ι → ℝ) (i : ι)
    (hShock : ∀ ω j, j ≠ i → 0 ≤ shock ω j) :
    Ω → ConditionedOpponentOrderStats := fun ω =>
  opponentOrderStats
    (exponentialRaceKey reserve temperature (shock ω) bids) i (by
      intro j hj
      exact div_nonneg (hShock ω j hj) (luceIntensity_pos reserve temperature (bids j)).le)

/-- Rank-`p` event for the bidder's own unit exponential shock, conditional on
the sorted opponent arrivals.  Intervals are left-open and right-closed, which
matches strict comparison of opponent arrival keys away from the null tie set. -/
noncomputable def conditionedShockRankEvent
    (stats : ConditionedOpponentOrderStats) (score : ℝ) (p : ℕ) : Set ℝ :=
  match p with
  | 0 =>
      match stats.threshold 0 with
      | none => Set.univ
      | some upper => Set.Iic (Real.exp score * upper)
  | q + 1 =>
      match stats.threshold q, stats.threshold (q + 1) with
      | some lower, some upper =>
          Set.Ioc (Real.exp score * lower) (Real.exp score * upper)
      | some lower, none => Set.Ioi (Real.exp score * lower)
      | none, _ => ∅

theorem conditionedShockRankEvent_measurable
    (stats : ConditionedOpponentOrderStats) (score : ℝ) (p : ℕ) :
    MeasurableSet (conditionedShockRankEvent stats score p) := by
  cases p with
  | zero =>
      cases h : stats.threshold 0 <;> simp [conditionedShockRankEvent, h]
  | succ p =>
      cases hp : stats.threshold p <;> cases hn : stats.threshold (p + 1) <;>
        simp [conditionedShockRankEvent, hp, hn]

theorem expMeasure_one_real_Iic (x : ℝ) (hx : 0 ≤ x) :
    (expMeasure 1).real (Set.Iic x) = 1 - Real.exp (-x) := by
  letI : IsProbabilityMeasure (expMeasure 1) :=
    isProbabilityMeasure_expMeasure (by norm_num)
  rw [← cdf_eq_real]
  rw [cdf_expMeasure_eq (by norm_num)]
  simp [hx]

theorem expMeasure_one_real_Ioi (x : ℝ) (hx : 0 ≤ x) :
    (expMeasure 1).real (Set.Ioi x) = Real.exp (-x) := by
  letI : IsProbabilityMeasure (expMeasure 1) :=
    isProbabilityMeasure_expMeasure (by norm_num)
  have hset : Set.Ioi x = Set.univ \ Set.Iic x := by
    ext y
    simp
  rw [hset, measureReal_diff (Set.subset_univ _) measurableSet_Iic]
  rw [← cdf_eq_real]
  rw [cdf_expMeasure_eq (by norm_num)]
  simp [hx]

theorem expMeasure_one_real_Ioc
    (a b : ℝ) (hab : a ≤ b) (ha : 0 ≤ a) (hb : 0 ≤ b) :
    (expMeasure 1).real (Set.Ioc a b) =
      Real.exp (-a) - Real.exp (-b) := by
  letI : IsProbabilityMeasure (expMeasure 1) :=
    isProbabilityMeasure_expMeasure (by norm_num)
  have hset : Set.Ioc a b = Set.Iic b \ Set.Iic a := by
    ext x
    simp only [Set.mem_Ioc, Set.mem_diff, Set.mem_Iic, not_le]
    exact ⟨fun hx => ⟨hx.2, hx.1⟩, fun hx => ⟨hx.2, hx.1⟩⟩
  rw [hset, measureReal_diff (Set.Iic_subset_Iic.mpr hab) measurableSet_Iic]
  rw [← cdf_eq_real, ← cdf_eq_real]
  rw [cdf_expMeasure_eq (by norm_num), cdf_expMeasure_eq (by norm_num)]
  simp [ha, hb]

/-- The probability of every actual own-clock rank interval is precisely the
rank mass appearing in the summation-by-parts formula. -/
theorem conditionedShockRankEvent_mass
    (stats : ConditionedOpponentOrderStats) (score : ℝ) (p : ℕ) :
    (expMeasure 1).real (conditionedShockRankEvent stats score p) =
      conditionedRankMass stats score p := by
  letI : IsProbabilityMeasure (expMeasure 1) :=
    isProbabilityMeasure_expMeasure (by norm_num)
  cases p with
  | zero =>
      cases h : stats.threshold 0 with
      | none =>
          simp [conditionedShockRankEvent, conditionedRankMass,
            previousConditionedSurvival, conditionedSurvival, h]
      | some t =>
          have ht := stats.nonnegative 0 t h
          have hscaled : 0 ≤ Real.exp score * t :=
            mul_nonneg (Real.exp_pos _).le ht
          rw [conditionedShockRankEvent, h, expMeasure_one_real_Iic _ hscaled]
          simp [conditionedRankMass, previousConditionedSurvival,
            conditionedSurvival, h]
  | succ p =>
      cases hp : stats.threshold p with
      | none =>
          have hn := stats.padding p hp
          simp [conditionedShockRankEvent, conditionedRankMass,
            previousConditionedSurvival, conditionedSurvival, hp, hn]
      | some t =>
          have ht := stats.nonnegative p t hp
          have htscaled : 0 ≤ Real.exp score * t :=
            mul_nonneg (Real.exp_pos _).le ht
          cases hn : stats.threshold (p + 1) with
          | none =>
              rw [conditionedShockRankEvent, hp, hn,
                expMeasure_one_real_Ioi _ htscaled]
              simp [conditionedRankMass, previousConditionedSurvival,
                conditionedSurvival, hp, hn]
          | some u =>
              have hu := stats.nonnegative (p + 1) u hn
              have htu := stats.ordered p t u hp hn
              have huscaled : 0 ≤ Real.exp score * u :=
                mul_nonneg (Real.exp_pos _).le hu
              have hscaledOrder :
                  Real.exp score * t ≤ Real.exp score * u :=
                mul_le_mul_of_nonneg_left htu (Real.exp_pos _).le
              rw [conditionedShockRankEvent, hp, hn,
                expMeasure_one_real_Ioc _ _ hscaledOrder htscaled huscaled]
              simp [conditionedRankMass, previousConditionedSurvival,
                conditionedSurvival, hp, hn]

/-- Realized top-`K` priority on the remaining one-dimensional exponential
sample space after opponent keys have been fixed. -/
noncomputable def conditionedFiniteRacePriority
    (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : ConditionedOpponentOrderStats) (score ownShock : ℝ) : ℝ :=
  ∑ p ∈ Finset.range slots,
    (conditionedShockRankEvent stats score p).indicator
      (fun _ => slotWeight p) ownShock

/-- Integrating the realized finite-race priority over the bidder's own
`Exp(1)` clock gives exactly the conditional interval priority. -/
theorem conditionedFiniteRacePriority_integral
    (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : ConditionedOpponentOrderStats) (score : ℝ) :
    ∫ ownShock, conditionedFiniteRacePriority slotWeight slots stats score ownShock
        ∂expMeasure 1 =
      conditionalIntervalPriority slotWeight slots stats score := by
  letI : IsProbabilityMeasure (expMeasure 1) :=
    isProbabilityMeasure_expMeasure (by norm_num)
  unfold conditionedFiniteRacePriority
  rw [integral_finsetSum]
  · apply Finset.sum_congr rfl
    intro p hp
    rw [integral_indicator_const (slotWeight p)
      (conditionedShockRankEvent_measurable stats score p)]
    rw [conditionedShockRankEvent_mass]
    simp [mul_comm]
  · intro p hp
    exact (integrable_const (slotWeight p)).integrableOn.integrable_indicator
      (conditionedShockRankEvent_measurable stats score p)

theorem conditionedFiniteRacePriority_integral_eq_conditionalPriority
    (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : ConditionedOpponentOrderStats) (score : ℝ)
    (hTerminal : slotWeight slots = 0) :
    ∫ ownShock, conditionedFiniteRacePriority slotWeight slots stats score ownShock
        ∂expMeasure 1 =
      conditionalPriority slotWeight slots stats score := by
  rw [conditionedFiniteRacePriority_integral]
  exact conditionalIntervalPriority_eq_abel slotWeight slots stats score hTerminal

/-- First integrate the bidder's own clock, then integrate the pushed opponent
order statistics.  No disintegration theorem is needed because both integrals
remain on their original sample spaces. -/
noncomputable def finiteRaceInterimPriority
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : Ω → ConditionedOpponentOrderStats)
    (reserve temperature bid : ℝ) : ℝ :=
  ∫ ω, ∫ ownShock,
      conditionedFiniteRacePriority slotWeight slots (stats ω)
        ((bid - reserve) / temperature) ownShock
      ∂expMeasure 1 ∂μ

theorem finiteRaceInterimPriority_eq_conditionedInterimPriority
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : Ω → ConditionedOpponentOrderStats)
    (reserve temperature bid : ℝ)
    (hTerminal : slotWeight slots = 0) :
    finiteRaceInterimPriority μ slotWeight slots stats reserve temperature bid =
      conditionedInterimPriority μ slotWeight slots stats reserve temperature bid := by
  unfold finiteRaceInterimPriority conditionedInterimPriority
  apply integral_congr_ae
  filter_upwards with ω
  exact conditionedFiniteRacePriority_integral_eq_conditionalPriority
    slotWeight slots (stats ω) ((bid - reserve) / temperature) hTerminal

noncomputable def finiteRaceReserveInterimPriority
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : Ω → ConditionedOpponentOrderStats)
    (reserve temperature bid : ℝ) : ℝ :=
  if bid < reserve then 0
  else finiteRaceInterimPriority μ slotWeight slots stats reserve temperature bid

theorem finiteRaceReserveInterimPriority_eq_conditioned
    {Ω : Type*} [MeasurableSpace Ω]
    (μ : Measure Ω) (slotWeight : ℕ → ℝ) (slots : ℕ)
    (stats : Ω → ConditionedOpponentOrderStats)
    (reserve temperature bid : ℝ)
    (hTerminal : slotWeight slots = 0) :
    finiteRaceReserveInterimPriority μ slotWeight slots stats reserve temperature bid =
      conditionedReserveInterimPriority μ slotWeight slots stats reserve temperature bid := by
  by_cases hBid : bid < reserve
  · simp [finiteRaceReserveInterimPriority, conditionedReserveInterimPriority, hBid]
  · simp [finiteRaceReserveInterimPriority, conditionedReserveInterimPriority, hBid,
      finiteRaceInterimPriority_eq_conditionedInterimPriority _ _ _ _ _ _ _ hTerminal]

/-- `generalTopKStability` instantiated on actual sorted finite opponent
exponential-race keys.  The only analytic premises left are measurability of the
two explicit finite-statistic functions; no derivative or Lipschitz conclusion
is assumed. -/
theorem finiteExponentialRaceTopKStability
    {Ω ι : Type*} [MeasurableSpace Ω] [Fintype ι] [DecidableEq ι]
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (slotWeight : ℕ → ℝ) (slots : ℕ)
    (reserve temperature : ℝ) (shock : Ω → ι → ℝ)
    (bids : ι → ℝ) (i : ι)
    (hShock : ∀ ω j, j ≠ i → 0 ≤ shock ω j)
    (hTemperature : 0 < temperature)
    (hWeight : Antitone slotWeight)
    (hTerminal : slotWeight slots = 0)
    (hPriorityMeasurable : ∀ z,
      AEMeasurable (fun ω => conditionalBidPriority slotWeight slots
        (plOpponentOrderStats reserve temperature shock bids i hShock ω)
        reserve temperature z) μ)
    (hDerivativeMeasurable : ∀ z,
      AEMeasurable (fun ω => conditionalBidDerivative slotWeight slots
        (plOpponentOrderStats reserve temperature shock bids i hShock ω)
        reserve temperature z) μ) :
    (∀ bid,
      HasDerivAt
        (finiteRaceInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature)
        (conditionedInterimDerivative μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature bid) bid ∧
      deriv
        (finiteRaceInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature) bid ∈
        Set.Icc 0 (slotWeight 0 / (Real.exp 1 * temperature))) ∧
    (∀ a b, reserve ≤ a → reserve ≤ b →
      |finiteRaceReserveInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature b -
        finiteRaceReserveInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature a| ≤
        (slotWeight 0 / (Real.exp 1 * temperature)) * |b - a|) := by
  let stats := plOpponentOrderStats reserve temperature shock bids i hShock
  have hGeneral := generalTopKStability μ slotWeight slots stats reserve temperature
    hTemperature hWeight hTerminal hPriorityMeasurable hDerivativeMeasurable
  dsimp only [stats] at hGeneral ⊢
  have hInterim :
      finiteRaceInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature =
        conditionedInterimPriority μ slotWeight slots
          (plOpponentOrderStats reserve temperature shock bids i hShock)
          reserve temperature := by
    funext z
    exact finiteRaceInterimPriority_eq_conditionedInterimPriority
      μ slotWeight slots
      (plOpponentOrderStats reserve temperature shock bids i hShock)
      reserve temperature z hTerminal
  constructor
  · intro bid
    constructor
    · rw [hInterim]
      exact (hGeneral.1 bid).1
    · rw [hInterim]
      exact (hGeneral.1 bid).2
  · intro a b ha hb
    rw [finiteRaceReserveInterimPriority_eq_conditioned
      μ slotWeight slots
      (plOpponentOrderStats reserve temperature shock bids i hShock)
      reserve temperature b hTerminal]
    rw [finiteRaceReserveInterimPriority_eq_conditioned
      μ slotWeight slots
      (plOpponentOrderStats reserve temperature shock bids i hShock)
      reserve temperature a hTerminal]
    exact hGeneral.2.1 a b ha hb

end SmoothingCliff.Mechanism
