import SmoothingCliff.Racing.ExactThreshold
import Mathlib.MeasureTheory.Integral.IntervalIntegral.Basic
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
import Mathlib.MeasureTheory.Integral.IntervalAverage
import Mathlib.Analysis.Calculus.Deriv.Slope
import Mathlib.Analysis.Calculus.Deriv.Inv
import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics

/-!
# Run-up averages in the exact racing threshold

This file isolates the analytic object used in part (i) of Proposition
`prop:exact_threshold`.  A positive own investment averages the logistic
marginal-value window over an interval.  Opponent investment translates that
interval to the left.

The order-theoretic dominance results below use genuine suprema.  In
particular, neither attainment of a supremum nor dominance is assumed.
-/

namespace SmoothingCliff.Racing

noncomputable section

/-- The marginal-value integrand for a run-up of player `i`, conditional on
the opponent's investment. -/
def runUpKernel
    (contestedBand opponentBand temperature opponentInvestment runUp : ℝ) : ℝ :=
  feasibleMarginalWindow contestedBand opponentBand temperature
    runUp opponentInvestment

/-- Total allocation-value gain along a positive run-up. -/
def runUpIntegral
    (contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ) : ℝ :=
  ∫ runUp in (0 : ℝ)..ownInvestment,
    runUpKernel contestedBand opponentBand temperature opponentInvestment runUp

/-- Average marginal allocation value along a run-up. -/
def runUpAverage
    (contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ) : ℝ :=
  runUpIntegral contestedBand opponentBand temperature ownInvestment
      opponentInvestment /
    ownInvestment

/-- The averages generated by positive own investment and nonnegative
opponent investment. -/
def feasibleRunUpAverages
    (contestedBand opponentBand temperature : ℝ) : Set ℝ :=
  {value | ∃ ownInvestment, 0 < ownInvestment ∧
    ∃ opponentInvestment, 0 ≤ opponentInvestment ∧
      value = runUpAverage contestedBand opponentBand temperature
        ownInvestment opponentInvestment}

/-- The actual supremum over all feasible run-up averages. -/
def feasibleRunUpSupremum
    (contestedBand opponentBand temperature : ℝ) : ℝ :=
  sSup (feasibleRunUpAverages contestedBand opponentBand temperature)

/-- The second branch in the paper: opponent investment is zero and the
positive run-up length is optimized. -/
def boundaryRunUpSupremum
    (contestedBand opponentBand temperature : ℝ) : ℝ :=
  sSup ((fun ownInvestment =>
    runUpAverage contestedBand opponentBand temperature ownInvestment 0) ''
      Set.Ioi 0)

/-- The paper's two-branch quantity `M_i`. -/
def runUpMaximum
    (contestedBand opponentBand temperature : ℝ) : ℝ :=
  if 2 * opponentBand ≤ contestedBand then
    2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1
  else
    boundaryRunUpSupremum contestedBand opponentBand temperature

/-- `M = max{M₁,M₂}` for two players. -/
def twoPlayerRunUpMaximum
    (firstBand secondBand temperature : ℝ) : ℝ :=
  max (runUpMaximum firstBand secondBand temperature)
    (runUpMaximum secondBand firstBand temperature)

/-- Zero weakly dominates every positive investment for one player, stated
directly in utility-gain form and uniformly over opponent investment. -/
def ZeroRunUpWeaklyDominates
    (slotWeight contestedBand opponentBand cost temperature : ℝ) : Prop :=
  ∀ ownInvestment, 0 < ownInvestment →
    ∀ opponentInvestment, 0 ≤ opponentInvestment →
      slotWeight *
          runUpIntegral contestedBand opponentBand temperature
            ownInvestment opponentInvestment ≤
        cost * ownInvestment

/-- Strict dominance of every positive investment. -/
def ZeroRunUpStrictlyDominates
    (slotWeight contestedBand opponentBand cost temperature : ℝ) : Prop :=
  ∀ ownInvestment, 0 < ownInvestment →
    ∀ opponentInvestment, 0 ≤ opponentInvestment →
      slotWeight *
          runUpIntegral contestedBand opponentBand temperature
            ownInvestment opponentInvestment <
        cost * ownInvestment

theorem runUpKernel_continuous
    (contestedBand opponentBand temperature opponentInvestment : ℝ) :
    Continuous
      (runUpKernel contestedBand opponentBand temperature opponentInvestment) := by
  unfold runUpKernel feasibleMarginalWindow marginalWindow
  fun_prop

theorem runUpKernel_intervalIntegrable
    (contestedBand opponentBand temperature opponentInvestment left right : ℝ) :
    IntervalIntegrable
      (runUpKernel contestedBand opponentBand temperature opponentInvestment)
      MeasureTheory.volume left right :=
  (runUpKernel_continuous contestedBand opponentBand temperature
    opponentInvestment).intervalIntegrable left right

/-- Strict form of the positive-variable centered-window inequality. -/
theorem inv_window_lt_center
    {x z : ℝ} (hx : 0 < x) (hz : 0 < z) (hzOne : z < 1)
    (hNotCenter : z * x ≠ 1) :
    (1 + z ^ 2 * x)⁻¹ - (1 + x)⁻¹ <
      (1 + z)⁻¹ - (1 + z⁻¹)⁻¹ := by
  have hOneX : 0 < 1 + x := by linarith
  have hOneZX : 0 < 1 + z ^ 2 * x := by positivity
  have hOneZ : 0 < 1 + z := by linarith
  have hLeft :
      (1 + z ^ 2 * x)⁻¹ - (1 + x)⁻¹ =
        x * (1 - z ^ 2) / ((1 + z ^ 2 * x) * (1 + x)) := by
    field_simp
    ring
  have hRight :
      (1 + z)⁻¹ - (1 + z⁻¹)⁻¹ = (1 - z) / (1 + z) := by
    field_simp [ne_of_gt hz]
    ring
  rw [hLeft, hRight]
  apply (div_lt_div_iff₀ (mul_pos hOneZX hOneX) hOneZ).2
  have hSquare : 0 < (1 - z * x) ^ 2 := by
    exact sq_pos_of_ne_zero (sub_ne_zero.mpr (Ne.symm hNotCenter))
  have hFactor : 0 < 1 - z := sub_pos.mpr hzOne
  have hIdentity :
      (1 - z) *
          ((1 + z ^ 2 * x) * (1 + x) - x * (1 + z) ^ 2) =
        (1 - z) * (1 - z * x) ^ 2 := by
    ring
  nlinarith [mul_pos hFactor hSquare]

/-- Away from its unique center, a positive-width logistic window is strictly
below its centered value. -/
theorem marginalWindow_lt_center
    {d temperature position : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < d)
    (hPosition : position ≠ -d / 2) :
    marginalWindow d temperature position <
      2 * Real.sigmoid (d / (2 * temperature)) - 1 := by
  let x := Real.exp (-(position / temperature))
  let z := Real.exp (-(d / (2 * temperature)))
  have hx : 0 < x := Real.exp_pos _
  have hz : 0 < z := Real.exp_pos _
  have hExponent : -(d / (2 * temperature)) < 0 := by
    have : 0 < d / (2 * temperature) :=
      div_pos hBand (mul_pos (by norm_num) hTemperature)
    linarith
  have hzOne : z < 1 := by
    dsimp [z]
    rw [← Real.exp_zero]
    exact (Real.exp_lt_exp).2 hExponent
  have hNotCenter : z * x ≠ 1 := by
    intro hProduct
    dsimp [z, x] at hProduct
    rw [← Real.exp_add] at hProduct
    have hZero := (Real.exp_eq_one_iff
      (-(d / (2 * temperature)) + -(position / temperature))).1 hProduct
    apply hPosition
    field_simp [ne_of_gt hTemperature] at hZero ⊢
    linarith
  have hAlgebra := inv_window_lt_center hx hz hzOne hNotCenter
  unfold marginalWindow Real.sigmoid
  have hFirstExponent :
      Real.exp (-((d + position) / temperature)) = z ^ 2 * x := by
    dsimp [z, x]
    rw [show -((d + position) / temperature) =
        -(d / (2 * temperature)) + (-(d / (2 * temperature))) +
          (-(position / temperature)) by
      field_simp
      ring]
    rw [Real.exp_add, Real.exp_add]
    ring
  have hxDef : Real.exp (-(position / temperature)) = x := by simp [x]
  have hzDef : Real.exp (-(d / (2 * temperature))) = z := by simp [z]
  rw [hFirstExponent, hxDef, hzDef]
  have hCenter :
      (1 + z)⁻¹ - (1 + z⁻¹)⁻¹ = 2 * (1 + z)⁻¹ - 1 := by
    field_simp [ne_of_gt hz]
    ring
  rw [← hCenter]
  exact hAlgebra

/-- On the increasing side of the rationalized logistic window, increasing
the exponential coordinate raises the window. -/
theorem inv_window_lt_of_product_lt_one
    {z smaller larger : ℝ}
    (hz : 0 < z) (hzOne : z < 1)
    (hSmaller : 0 < smaller) (hOrder : smaller < larger)
    (hProduct : z * smaller * larger < 1) :
    (1 + z * smaller)⁻¹ - (1 + smaller)⁻¹ <
      (1 + z * larger)⁻¹ - (1 + larger)⁻¹ := by
  have hLarger : 0 < larger := lt_trans hSmaller hOrder
  have hDs : 0 < (1 + z * smaller) * (1 + smaller) := by positivity
  have hDl : 0 < (1 + z * larger) * (1 + larger) := by positivity
  have hRewrite (x : ℝ) (hx : 0 < x) :
      (1 + z * x)⁻¹ - (1 + x)⁻¹ =
        x * (1 - z) / ((1 + z * x) * (1 + x)) := by
    field_simp
    ring
  rw [hRewrite smaller hSmaller, hRewrite larger hLarger]
  apply (div_lt_div_iff₀ hDs hDl).2
  have hPositive :
      0 < (larger - smaller) * (1 - z) *
        (1 - z * smaller * larger) := by positivity
  have hIdentity :
      larger * (1 - z) * ((1 + z * smaller) * (1 + smaller)) -
          smaller * (1 - z) * ((1 + z * larger) * (1 + larger)) =
        (larger - smaller) * (1 - z) *
          (1 - z * smaller * larger) := by
    ring
  nlinarith

/-- On the other side of the peak, the same exponential comparison reverses. -/
theorem inv_window_lt_of_one_lt_product
    {z smaller larger : ℝ}
    (hz : 0 < z) (hzOne : z < 1)
    (hSmaller : 0 < smaller) (hOrder : smaller < larger)
    (hProduct : 1 < z * smaller * larger) :
    (1 + z * larger)⁻¹ - (1 + larger)⁻¹ <
      (1 + z * smaller)⁻¹ - (1 + smaller)⁻¹ := by
  have hLarger : 0 < larger := lt_trans hSmaller hOrder
  have hDs : 0 < (1 + z * smaller) * (1 + smaller) := by positivity
  have hDl : 0 < (1 + z * larger) * (1 + larger) := by positivity
  have hRewrite (x : ℝ) (hx : 0 < x) :
      (1 + z * x)⁻¹ - (1 + x)⁻¹ =
        x * (1 - z) / ((1 + z * x) * (1 + x)) := by
    field_simp
    ring
  rw [hRewrite larger hLarger, hRewrite smaller hSmaller]
  apply (div_lt_div_iff₀ hDl hDs).2
  have hPositive :
      0 < (larger - smaller) * (1 - z) *
        (z * smaller * larger - 1) := by positivity
  have hIdentity :
      smaller * (1 - z) * ((1 + z * larger) * (1 + larger)) -
          larger * (1 - z) * ((1 + z * smaller) * (1 + smaller)) =
        (larger - smaller) * (1 - z) *
          (z * smaller * larger - 1) := by
    ring
  nlinarith

/-- The logistic window is strictly increasing to its center. -/
theorem marginalWindow_strictMonoOn_left
    {d temperature : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < d) :
    StrictMonoOn (marginalWindow d temperature) (Set.Iic (-d / 2)) := by
  intro first hFirst second hSecond hOrder
  let z := Real.exp (-(d / temperature))
  let xFirst := Real.exp (-(first / temperature))
  let xSecond := Real.exp (-(second / temperature))
  have hz : 0 < z := Real.exp_pos _
  have hxSecond : 0 < xSecond := Real.exp_pos _
  have hzOne : z < 1 := by
    dsimp [z]
    rw [← Real.exp_zero]
    apply (Real.exp_lt_exp).2
    have : 0 < d / temperature := div_pos hBand hTemperature
    linarith
  have hxOrder : xSecond < xFirst := by
    dsimp [xSecond, xFirst]
    apply (Real.exp_lt_exp).2
    exact neg_lt_neg (div_lt_div_of_pos_right hOrder hTemperature)
  have hProduct : 1 < z * xSecond * xFirst := by
    change first ≤ -d / 2 at hFirst
    change second ≤ -d / 2 at hSecond
    have hSum : d + first + second < 0 := by
      linarith
    have hExpIdentity :
        z * xSecond * xFirst =
          Real.exp (-((d + first + second) / temperature)) := by
      dsimp [z, xSecond, xFirst]
      rw [← Real.exp_add, ← Real.exp_add]
      congr 1
      field_simp [ne_of_gt hTemperature]
      ring
    rw [hExpIdentity, ← Real.exp_zero]
    apply (Real.exp_lt_exp).2
    have : 0 < -((d + first + second) / temperature) := by
      exact neg_pos.mpr (div_neg_of_neg_of_pos hSum hTemperature)
    linarith
  have hAlgebra := inv_window_lt_of_one_lt_product
    hz hzOne hxSecond hxOrder hProduct
  unfold marginalWindow Real.sigmoid
  have hFirstExp :
      Real.exp (-((d + first) / temperature)) = z * xFirst := by
    dsimp [z, xFirst]
    rw [← Real.exp_add]
    congr 1
    field_simp [ne_of_gt hTemperature]
    ring
  have hSecondExp :
      Real.exp (-((d + second) / temperature)) = z * xSecond := by
    dsimp [z, xSecond]
    rw [← Real.exp_add]
    congr 1
    field_simp [ne_of_gt hTemperature]
    ring
  rw [hFirstExp, hSecondExp]
  simpa [xFirst, xSecond] using hAlgebra

/-- The logistic window is strictly decreasing after its center. -/
theorem marginalWindow_strictAntiOn_right
    {d temperature : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < d) :
    StrictAntiOn (marginalWindow d temperature) (Set.Ici (-d / 2)) := by
  intro first hFirst second hSecond hOrder
  let z := Real.exp (-(d / temperature))
  let xFirst := Real.exp (-(first / temperature))
  let xSecond := Real.exp (-(second / temperature))
  have hz : 0 < z := Real.exp_pos _
  have hxSecond : 0 < xSecond := Real.exp_pos _
  have hzOne : z < 1 := by
    dsimp [z]
    rw [← Real.exp_zero]
    apply (Real.exp_lt_exp).2
    have : 0 < d / temperature := div_pos hBand hTemperature
    linarith
  have hxOrder : xSecond < xFirst := by
    dsimp [xSecond, xFirst]
    apply (Real.exp_lt_exp).2
    exact neg_lt_neg (div_lt_div_of_pos_right hOrder hTemperature)
  have hProduct : z * xSecond * xFirst < 1 := by
    change -d / 2 ≤ first at hFirst
    change -d / 2 ≤ second at hSecond
    have hSum : 0 < d + first + second := by
      linarith
    have hExpIdentity :
        z * xSecond * xFirst =
          Real.exp (-((d + first + second) / temperature)) := by
      dsimp [z, xSecond, xFirst]
      rw [← Real.exp_add, ← Real.exp_add]
      congr 1
      field_simp [ne_of_gt hTemperature]
      ring
    rw [hExpIdentity, ← Real.exp_zero]
    apply (Real.exp_lt_exp).2
    exact neg_neg_of_pos (div_pos hSum hTemperature)
  have hAlgebra := inv_window_lt_of_product_lt_one
    hz hzOne hxSecond hxOrder hProduct
  unfold marginalWindow Real.sigmoid
  have hFirstExp :
      Real.exp (-((d + first) / temperature)) = z * xFirst := by
    dsimp [z, xFirst]
    rw [← Real.exp_add]
    congr 1
    field_simp [ne_of_gt hTemperature]
    ring
  have hSecondExp :
      Real.exp (-((d + second) / temperature)) = z * xSecond := by
    dsimp [z, xSecond]
    rw [← Real.exp_add]
    congr 1
    field_simp [ne_of_gt hTemperature]
    ring
  rw [hFirstExp, hSecondExp]
  simpa [xFirst, xSecond] using hAlgebra

theorem marginalWindow_pos
    {d temperature position : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < d) :
    0 < marginalWindow d temperature position := by
  unfold marginalWindow
  apply sub_pos.mpr
  apply Real.sigmoid_lt
  exact div_lt_div_of_pos_right (by linarith) hTemperature

/-- A logistic window is at most the exponential attached to its left
endpoint. -/
theorem inv_window_le_exponential
    {z x : ℝ} (hz : 0 < z) (hzOne : z ≤ 1) (hx : 0 < x) :
    (1 + z * x)⁻¹ - (1 + x)⁻¹ ≤ x := by
  have hDenominator : 0 < (1 + z * x) * (1 + x) := by positivity
  have hRewrite :
      (1 + z * x)⁻¹ - (1 + x)⁻¹ =
        x * (1 - z) / ((1 + z * x) * (1 + x)) := by
    field_simp
    ring
  rw [hRewrite]
  apply (div_le_iff₀ hDenominator).2
  have hOneLe : 1 ≤ (1 + z * x) * (1 + x) := by
    nlinarith [mul_nonneg (le_of_lt hz) (le_of_lt hx)]
  have hOneMinus : 0 ≤ 1 - z := sub_nonneg.mpr hzOne
  nlinarith

theorem marginalWindow_le_exp_neg
    {d temperature position : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 ≤ d) :
    marginalWindow d temperature position ≤
      Real.exp (-(position / temperature)) := by
  let z := Real.exp (-(d / temperature))
  let x := Real.exp (-(position / temperature))
  have hz : 0 < z := Real.exp_pos _
  have hx : 0 < x := Real.exp_pos _
  have hzOne : z ≤ 1 := by
    dsimp [z]
    rw [← Real.exp_zero]
    apply (Real.exp_le_exp).2
    exact neg_nonpos.mpr (div_nonneg hBand (le_of_lt hTemperature))
  have hAlgebra := inv_window_le_exponential hz hzOne hx
  unfold marginalWindow Real.sigmoid
  have hFirstExp :
      Real.exp (-((d + position) / temperature)) = z * x := by
    dsimp [z, x]
    rw [← Real.exp_add]
    congr 1
    field_simp [ne_of_gt hTemperature]
    ring
  rw [hFirstExp]
  simpa [x] using hAlgebra

/-- The endpoint term in the first-order condition vanishes in the tail. -/
theorem boundaryKernel_mul_tendsto_zero_atTop
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand) :
    Filter.Tendsto
      (fun length => length *
        runUpKernel contestedBand opponentBand temperature 0 length)
      Filter.atTop (nhds 0) := by
  have hExponentialTail :
      Filter.Tendsto
        (fun length : ℝ =>
          length * Real.exp (-((length - opponentBand) / temperature)))
        Filter.atTop (nhds 0) := by
    have hTail :
        Filter.Tendsto
          (fun length : ℝ => length * Real.exp (-(length / temperature)))
          Filter.atTop (nhds 0) := by
      have h := tendsto_rpow_mul_exp_neg_mul_atTop_nhds_zero
        (1 : ℝ) (1 / temperature) (one_div_pos.mpr hTemperature)
      simpa [Real.rpow_one, div_eq_mul_inv, mul_comm] using h
    have hConstant :
        Filter.Tendsto (fun _ : ℝ => Real.exp (opponentBand / temperature))
          Filter.atTop (nhds (Real.exp (opponentBand / temperature))) :=
      tendsto_const_nhds
    have hScaled := hConstant.mul hTail
    convert hScaled using 1
    · funext length
      have hExp :
          Real.exp (-((length - opponentBand) / temperature)) =
            Real.exp (opponentBand / temperature) *
              Real.exp (-(length / temperature)) := by
        rw [← Real.exp_add]
        congr 1
        field_simp [ne_of_gt hTemperature]
        ring
      rw [hExp]
      ring
    · simp
  refine squeeze_zero'
    (f := fun length => length *
      runUpKernel contestedBand opponentBand temperature 0 length)
    (g := fun length =>
      length * Real.exp (-((length - opponentBand) / temperature))) ?_ ?_
      hExponentialTail
  · filter_upwards [Filter.eventually_ge_atTop (0 : ℝ)] with length hLength
    exact mul_nonneg hLength
      (le_of_lt (by
        unfold runUpKernel feasibleMarginalWindow
        exact marginalWindow_pos hTemperature hBand))
  · filter_upwards [Filter.eventually_ge_atTop (0 : ℝ)] with length hLength
    apply mul_le_mul_of_nonneg_left _ hLength
    unfold runUpKernel feasibleMarginalWindow
    simpa using (marginalWindow_le_exp_neg
      (position := length - opponentBand) hTemperature (le_of_lt hBand))

/-- Run-up coordinate of the pointwise peak in the boundary problem. -/
def boundaryPeak (contestedBand opponentBand : ℝ) : ℝ :=
  opponentBand - contestedBand / 2

/-- Numerator of the derivative of the boundary prefix average. -/
def boundaryRunUpGap
    (contestedBand opponentBand temperature length : ℝ) : ℝ :=
  length * runUpKernel contestedBand opponentBand temperature 0 length -
    runUpIntegral contestedBand opponentBand temperature length 0

theorem boundaryKernel_strictMonoOn_beforePeak
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < contestedBand) :
    StrictMonoOn (runUpKernel contestedBand opponentBand temperature 0)
      (Set.Iic (boundaryPeak contestedBand opponentBand)) := by
  intro first hFirst second hSecond hOrder
  unfold runUpKernel feasibleMarginalWindow
  apply marginalWindow_strictMonoOn_left hTemperature hBand
  · change first ≤ boundaryPeak contestedBand opponentBand at hFirst
    unfold boundaryPeak at hFirst
    change first - opponentBand - 0 ≤ -contestedBand / 2
    linarith
  · change second ≤ boundaryPeak contestedBand opponentBand at hSecond
    unfold boundaryPeak at hSecond
    change second - opponentBand - 0 ≤ -contestedBand / 2
    linarith
  · linarith

theorem boundaryKernel_strictAntiOn_afterPeak
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature) (hBand : 0 < contestedBand) :
    StrictAntiOn (runUpKernel contestedBand opponentBand temperature 0)
      (Set.Ici (boundaryPeak contestedBand opponentBand)) := by
  intro first hFirst second hSecond hOrder
  unfold runUpKernel feasibleMarginalWindow
  apply marginalWindow_strictAntiOn_right hTemperature hBand
  · change boundaryPeak contestedBand opponentBand ≤ first at hFirst
    unfold boundaryPeak at hFirst
    change -contestedBand / 2 ≤ first - opponentBand - 0
    linarith
  · change boundaryPeak contestedBand opponentBand ≤ second at hSecond
    unfold boundaryPeak at hSecond
    change -contestedBand / 2 ≤ second - opponentBand - 0
    linarith
  · linarith

/-- Before (and including) the pointwise peak, the moving-average derivative
numerator is strictly positive. -/
theorem boundaryRunUpGap_pos_beforePeak
    {contestedBand opponentBand temperature length : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hLength : 0 < length)
    (hBefore : length ≤ boundaryPeak contestedBand opponentBand) :
    0 < boundaryRunUpGap contestedBand opponentBand temperature length := by
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hStrictMono := boundaryKernel_strictMonoOn_beforePeak
    (opponentBand := opponentBand) hTemperature hBand
  have hIntegral :
      (∫ point in (0 : ℝ)..length, kernel point) <
        ∫ _point in (0 : ℝ)..length, kernel length := by
    exact intervalIntegral.integral_lt_integral_of_continuousOn_of_le_of_exists_lt
      hLength hContinuous.continuousOn continuous_const.continuousOn
      (fun point hPoint =>
        (hStrictMono.monotoneOn
          (show point ∈ Set.Iic (boundaryPeak contestedBand opponentBand) by
            exact le_trans hPoint.2 hBefore)
          (show length ∈ Set.Iic (boundaryPeak contestedBand opponentBand) by
            exact hBefore)
          hPoint.2))
      ⟨0, ⟨le_rfl, le_of_lt hLength⟩,
        hStrictMono
          (show (0 : ℝ) ∈ Set.Iic
              (boundaryPeak contestedBand opponentBand) by
            exact le_of_lt hPeakPos)
          (show length ∈ Set.Iic (boundaryPeak contestedBand opponentBand) by
            exact hBefore)
          hLength⟩
  simp only [intervalIntegral.integral_const, sub_zero, smul_eq_mul] at hIntegral
  unfold boundaryRunUpGap runUpIntegral
  dsimp [kernel] at hIntegral
  linarith

/-- The derivative numerator is strictly decreasing after the pointwise peak. -/
theorem boundaryRunUpGap_strictAntiOn_afterPeak
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    StrictAntiOn (boundaryRunUpGap contestedBand opponentBand temperature)
      (Set.Ici (boundaryPeak contestedBand opponentBand)) := by
  intro first hFirst second hSecond hOrder
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hStrictAnti := boundaryKernel_strictAntiOn_afterPeak
    (opponentBand := opponentBand) hTemperature hBand
  have hKernelOrder : kernel second < kernel first :=
    hStrictAnti hFirst hSecond hOrder
  have hTailLower :
      (second - first) * kernel second ≤
        ∫ point in first..second, kernel point := by
    have hIntegral :
        (∫ _point in first..second, kernel second) ≤
          ∫ point in first..second, kernel point := by
      exact intervalIntegral.integral_mono_on (le_of_lt hOrder)
        (continuous_const.intervalIntegrable first second)
        (hContinuous.intervalIntegrable first second)
        (fun point hPoint =>
          hStrictAnti.antitoneOn
            (show point ∈ Set.Ici (boundaryPeak contestedBand opponentBand) by
              exact le_trans hFirst hPoint.1)
            hSecond hPoint.2)
    simpa only [intervalIntegral.integral_const, smul_eq_mul] using hIntegral
  have hAdd := intervalIntegral.integral_add_adjacent_intervals
    (μ := MeasureTheory.volume)
    (hContinuous.intervalIntegrable 0 first)
    (hContinuous.intervalIntegrable first second)
  unfold boundaryRunUpGap runUpIntegral
  dsimp [kernel] at hKernelOrder hTailLower hAdd ⊢
  have hFirstPos : 0 < first := lt_of_lt_of_le hPeakPos hFirst
  nlinarith

theorem boundaryRunUpGap_continuous
    (contestedBand opponentBand temperature : ℝ) :
    Continuous (boundaryRunUpGap contestedBand opponentBand temperature) := by
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  have hPrimitive :
      Continuous (fun upper => ∫ point in (0 : ℝ)..upper, kernel point) := by
    rw [continuous_iff_continuousAt]
    intro upper
    exact (hContinuous.integral_hasStrictDerivAt 0 upper).hasDerivAt.continuousAt
  unfold boundaryRunUpGap runUpIntegral
  simpa [kernel] using (continuous_id.mul hContinuous).sub hPrimitive

/-- The quotient-rule identity `A'(a)=Q(a)/a²`. -/
theorem boundaryRunUpAverage_hasDerivAt
    {contestedBand opponentBand temperature length : ℝ}
    (hLength : 0 < length) :
    HasDerivAt
      (fun upper => runUpAverage contestedBand opponentBand temperature upper 0)
      (boundaryRunUpGap contestedBand opponentBand temperature length /
        length ^ 2) length := by
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  change HasDerivAt
    (fun upper : ℝ => (∫ point in (0 : ℝ)..upper, kernel point) / upper)
    ((length * kernel length - ∫ point in (0 : ℝ)..length, kernel point) /
      length ^ 2) length
  simpa [mul_comm] using
    (hContinuous.integral_hasStrictDerivAt 0 length).hasDerivAt.div
      (hasDerivAt_id' length) hLength.ne'

/-- Far enough past the pointwise peak, the derivative numerator is negative. -/
theorem exists_boundaryRunUpGap_neg_afterPeak
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    ∃ length, boundaryPeak contestedBand opponentBand < length ∧
      boundaryRunUpGap contestedBand opponentBand temperature length < 0 := by
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  let peak := boundaryPeak contestedBand opponentBand
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  have hPeakPos : 0 < peak := by
    dsimp [peak, boundaryPeak]
    linarith
  have hKernelPos : ∀ point, 0 < kernel point := by
    intro point
    dsimp [kernel, runUpKernel, feasibleMarginalWindow]
    exact marginalWindow_pos hTemperature hBand
  have hCorePositive : 0 < ∫ point in (0 : ℝ)..peak, kernel point :=
    intervalIntegral.intervalIntegral_pos_of_pos
      (hContinuous.intervalIntegrable 0 peak) hKernelPos hPeakPos
  have hTail :
      Filter.Tendsto (fun length => length * kernel length)
        Filter.atTop (nhds 0) := by
    simpa [kernel] using
      boundaryKernel_mul_tendsto_zero_atTop
        (opponentBand := opponentBand) hTemperature hBand
  have hEventuallySmall :
      ∀ᶠ length in Filter.atTop,
        length * kernel length < ∫ point in (0 : ℝ)..peak, kernel point :=
    hTail.eventually (Iio_mem_nhds hCorePositive)
  have hEventuallyPast :
      ∀ᶠ length in Filter.atTop, peak < length :=
    Filter.eventually_gt_atTop peak
  have hEventuallyBoth :
      ∀ᶠ length in Filter.atTop,
        peak < length ∧
          length * kernel length < ∫ point in (0 : ℝ)..peak, kernel point := by
    filter_upwards [hEventuallyPast, hEventuallySmall] with length hPast hSmall
    exact ⟨hPast, hSmall⟩
  obtain ⟨length, hPast, hSmall⟩ := hEventuallyBoth.exists
  have hTailNonnegative :
      0 ≤ ∫ point in peak..length, kernel point :=
    intervalIntegral.integral_nonneg (le_of_lt hPast)
      (fun point _ => le_of_lt (hKernelPos point))
  have hAdd := intervalIntegral.integral_add_adjacent_intervals
    (μ := MeasureTheory.volume)
    (hContinuous.intervalIntegrable 0 peak)
    (hContinuous.intervalIntegrable peak length)
  refine ⟨length, hPast, ?_⟩
  unfold boundaryRunUpGap runUpIntegral
  dsimp [kernel, peak] at hSmall hTailNonnegative hAdd ⊢
  nlinarith

/-- The second branch has a unique positive first-order root, and it lies
strictly after the pointwise peak `d_j-d_i/2`. -/
theorem existsUnique_boundaryRunUpGap_zero
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    ∃! optimalLength,
      boundaryPeak contestedBand opponentBand < optimalLength ∧
        boundaryRunUpGap contestedBand opponentBand temperature optimalLength = 0 := by
  let peak := boundaryPeak contestedBand opponentBand
  have hPeakPos : 0 < peak := by
    dsimp [peak, boundaryPeak]
    linarith
  have hGapPeak :
      0 < boundaryRunUpGap contestedBand opponentBand temperature peak := by
    dsimp [peak]
    exact boundaryRunUpGap_pos_beforePeak hTemperature hBand hBranch
      hPeakPos le_rfl
  obtain ⟨upper, hPeakUpper, hGapUpper⟩ :=
    exists_boundaryRunUpGap_neg_afterPeak hTemperature hBand hBranch
  have hContinuous := boundaryRunUpGap_continuous
    contestedBand opponentBand temperature
  have hZeroImage :
      (0 : ℝ) ∈
        boundaryRunUpGap contestedBand opponentBand temperature ''
          Set.Icc peak upper := by
    apply (intermediate_value_Icc' (le_of_lt hPeakUpper)
      hContinuous.continuousOn)
    exact ⟨le_of_lt hGapUpper, le_of_lt hGapPeak⟩
  obtain ⟨optimalLength, hOptimalInterval, hOptimalZero⟩ := hZeroImage
  have hPeakOptimal : peak < optimalLength := by
    have hNotEqual : peak ≠ optimalLength := by
      intro hEqual
      subst optimalLength
      linarith
    exact lt_of_le_of_ne hOptimalInterval.1 hNotEqual
  refine ⟨optimalLength, ⟨hPeakOptimal, hOptimalZero⟩, ?_⟩
  intro other hOther
  have hStrictAnti := boundaryRunUpGap_strictAntiOn_afterPeak
    hTemperature hBand hBranch
  apply hStrictAnti.injOn
  · exact le_of_lt hOther.1
  · exact le_of_lt hPeakOptimal
  · rw [hOther.2, hOptimalZero]

/-- At the unique second-branch optimum, the endpoint value equals the moving
average, exactly as in the paper's displayed first-order condition. -/
theorem boundaryRunUpGap_zero_iff_endpoint_eq_average
    {contestedBand opponentBand temperature length : ℝ}
    (hLength : 0 < length) :
    boundaryRunUpGap contestedBand opponentBand temperature length = 0 ↔
      runUpKernel contestedBand opponentBand temperature 0 length =
        runUpAverage contestedBand opponentBand temperature length 0 := by
  unfold boundaryRunUpGap runUpAverage
  constructor
  · intro hGap
    apply (eq_div_iff hLength.ne').2
    nlinarith
  · intro hEndpoint
    apply (eq_div_iff hLength.ne').1 at hEndpoint
    nlinarith

theorem boundaryRunUpAverage_continuousOn_pos
    (contestedBand opponentBand temperature : ℝ) :
    ContinuousOn
      (fun length =>
        runUpAverage contestedBand opponentBand temperature length 0)
      (Set.Ioi 0) := by
  intro length hLength
  exact (boundaryRunUpAverage_hasDerivAt hLength).continuousAt.continuousWithinAt

theorem boundaryRunUpGap_pos_before_root
    {contestedBand opponentBand temperature root length : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0)
    (hLength : 0 < length) (hLengthRoot : length < root) :
    0 < boundaryRunUpGap contestedBand opponentBand temperature length := by
  by_cases hBefore : length ≤ boundaryPeak contestedBand opponentBand
  · exact boundaryRunUpGap_pos_beforePeak hTemperature hBand hBranch
      hLength hBefore
  · have hPeakLength : boundaryPeak contestedBand opponentBand < length :=
      lt_of_not_ge hBefore
    have hStrictAnti := boundaryRunUpGap_strictAntiOn_afterPeak
      hTemperature hBand hBranch
    have hOrder := hStrictAnti
      (show length ∈ Set.Ici (boundaryPeak contestedBand opponentBand) by
        exact le_of_lt hPeakLength)
      (show root ∈ Set.Ici (boundaryPeak contestedBand opponentBand) by
        exact le_of_lt hRootPeak)
      hLengthRoot
    rw [hRootZero] at hOrder
    exact hOrder

theorem boundaryRunUpGap_neg_after_root
    {contestedBand opponentBand temperature root length : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0)
    (hRootLength : root < length) :
    boundaryRunUpGap contestedBand opponentBand temperature length < 0 := by
  have hStrictAnti := boundaryRunUpGap_strictAntiOn_afterPeak
    hTemperature hBand hBranch
  have hOrder := hStrictAnti
    (show root ∈ Set.Ici (boundaryPeak contestedBand opponentBand) by
      exact le_of_lt hRootPeak)
    (show length ∈ Set.Ici (boundaryPeak contestedBand opponentBand) by
      exact le_trans (le_of_lt hRootPeak) (le_of_lt hRootLength))
    hRootLength
  rw [hRootZero] at hOrder
  exact hOrder

theorem boundaryRunUpAverage_strictMonoOn_to_root
    {contestedBand opponentBand temperature root : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0) :
    StrictMonoOn
      (fun length =>
        runUpAverage contestedBand opponentBand temperature length 0)
      (Set.Ioc 0 root) := by
  have hRootPos : 0 < root := by
    have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
      unfold boundaryPeak
      linarith
    linarith
  apply strictMonoOn_of_hasDerivWithinAt_pos (convex_Ioc 0 root)
  · exact (boundaryRunUpAverage_continuousOn_pos contestedBand opponentBand
      temperature).mono (by
        intro length hLength
        exact hLength.1)
  · intro length hLength
    rw [interior_Ioc] at hLength
    exact (boundaryRunUpAverage_hasDerivAt hLength.1).hasDerivWithinAt
  · intro length hLength
    rw [interior_Ioc] at hLength
    exact div_pos
      (boundaryRunUpGap_pos_before_root hTemperature hBand hBranch
        hRootPeak hRootZero hLength.1 hLength.2)
      (sq_pos_of_pos hLength.1)

theorem boundaryRunUpAverage_strictAntiOn_after_root
    {contestedBand opponentBand temperature root : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0) :
    StrictAntiOn
      (fun length =>
        runUpAverage contestedBand opponentBand temperature length 0)
      (Set.Ici root) := by
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hRootPos : 0 < root := lt_trans hPeakPos hRootPeak
  apply strictAntiOn_of_hasDerivWithinAt_neg (convex_Ici root)
  · exact (boundaryRunUpAverage_continuousOn_pos contestedBand opponentBand
      temperature).mono (by
        intro length hLength
        exact lt_of_lt_of_le hRootPos hLength)
  · intro length hLength
    rw [interior_Ici] at hLength
    exact (boundaryRunUpAverage_hasDerivAt
      (lt_trans hRootPos hLength)).hasDerivWithinAt
  · intro length hLength
    rw [interior_Ici] at hLength
    exact div_neg_of_neg_of_pos
      (boundaryRunUpGap_neg_after_root hTemperature hBand hBranch
        hRootPeak hRootZero hLength)
      (sq_pos_of_pos (lt_trans hRootPos hLength))

/-- A root of the endpoint-average equation is the unique global maximizer
over all positive boundary run-up lengths. -/
theorem boundaryRunUpAverage_isGreatest_at_root
    {contestedBand opponentBand temperature root : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0) :
    IsGreatest
      ((fun length =>
        runUpAverage contestedBand opponentBand temperature length 0) ''
          Set.Ioi 0)
      (runUpAverage contestedBand opponentBand temperature root 0) := by
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hRootPos : 0 < root := lt_trans hPeakPos hRootPeak
  have hIncreasing := boundaryRunUpAverage_strictMonoOn_to_root
    hTemperature hBand hBranch hRootPeak hRootZero
  have hDecreasing := boundaryRunUpAverage_strictAntiOn_after_root
    hTemperature hBand hBranch hRootPeak hRootZero
  constructor
  · exact ⟨root, hRootPos, rfl⟩
  · rintro value ⟨length, hLength, rfl⟩
    by_cases hLengthRoot : length ≤ root
    · exact hIncreasing.monotoneOn
        ⟨hLength, hLengthRoot⟩ ⟨hRootPos, le_rfl⟩ hLengthRoot
    · have hRootLength : root < length := lt_of_not_ge hLengthRoot
      exact le_of_lt
        (hDecreasing (show root ≤ root from le_rfl)
          (show root ≤ length from le_of_lt hRootLength) hRootLength)

theorem boundaryRunUpAverage_unique_maximizer
    {contestedBand opponentBand temperature root length : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hRootPeak : boundaryPeak contestedBand opponentBand < root)
    (hRootZero :
      boundaryRunUpGap contestedBand opponentBand temperature root = 0)
    (hLength : 0 < length) :
    runUpAverage contestedBand opponentBand temperature length 0 =
        runUpAverage contestedBand opponentBand temperature root 0 ↔
      length = root := by
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hRootPos : 0 < root := lt_trans hPeakPos hRootPeak
  have hIncreasing := boundaryRunUpAverage_strictMonoOn_to_root
    hTemperature hBand hBranch hRootPeak hRootZero
  have hDecreasing := boundaryRunUpAverage_strictAntiOn_after_root
    hTemperature hBand hBranch hRootPeak hRootZero
  constructor
  · intro hEqual
    by_contra hNotEqual
    rcases lt_or_gt_of_ne hNotEqual with hLess | hGreater
    · have hStrict := hIncreasing
        (show length ∈ Set.Ioc 0 root by exact ⟨hLength, le_of_lt hLess⟩)
        (show root ∈ Set.Ioc 0 root by exact ⟨hRootPos, le_rfl⟩) hLess
      linarith
    · have hStrict := hDecreasing
        (show root ≤ root from le_rfl)
        (show root ≤ length from le_of_lt hGreater) hGreater
      linarith
  · rintro rfl
    rfl

/-- Full second-branch certificate: the prefix supremum is attained at a
unique `a_i^* > d_j-d_i/2`, and its endpoint equals its moving average. -/
theorem existsUnique_boundaryRunUpAverage_maximizer
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    ∃! optimalLength,
      boundaryPeak contestedBand opponentBand < optimalLength ∧
        boundaryRunUpSupremum contestedBand opponentBand temperature =
          runUpAverage contestedBand opponentBand temperature optimalLength 0 ∧
        runUpKernel contestedBand opponentBand temperature 0 optimalLength =
          runUpAverage contestedBand opponentBand temperature optimalLength 0 := by
  obtain ⟨optimalLength, hOptimal, hUnique⟩ :=
    existsUnique_boundaryRunUpGap_zero hTemperature hBand hBranch
  have hPeakPos : 0 < boundaryPeak contestedBand opponentBand := by
    unfold boundaryPeak
    linarith
  have hOptimalPos : 0 < optimalLength := lt_trans hPeakPos hOptimal.1
  have hGreatest := boundaryRunUpAverage_isGreatest_at_root
    hTemperature hBand hBranch hOptimal.1 hOptimal.2
  have hSupremum :
      boundaryRunUpSupremum contestedBand opponentBand temperature =
        runUpAverage contestedBand opponentBand temperature optimalLength 0 := by
    unfold boundaryRunUpSupremum
    exact hGreatest.csSup_eq
  have hEndpoint :=
    (boundaryRunUpGap_zero_iff_endpoint_eq_average hOptimalPos).1 hOptimal.2
  refine ⟨optimalLength, ⟨hOptimal.1, hSupremum, hEndpoint⟩, ?_⟩
  intro other hOther
  apply hUnique
  exact ⟨hOther.1,
    (boundaryRunUpGap_zero_iff_endpoint_eq_average
      (lt_trans hPeakPos hOther.1)).2 hOther.2.2⟩

/-- Prefix averages converge to the endpoint value as their positive length
tends to zero. -/
theorem runUpAverage_tendsto_zero
    (contestedBand opponentBand temperature opponentInvestment : ℝ) :
    Filter.Tendsto
      (fun ownInvestment =>
        runUpAverage contestedBand opponentBand temperature ownInvestment
          opponentInvestment)
      (nhdsWithin 0 (Set.Ioi 0))
      (nhds (runUpKernel contestedBand opponentBand temperature
        opponentInvestment 0)) := by
  let kernel := runUpKernel contestedBand opponentBand temperature
    opponentInvestment
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature
      opponentInvestment
  have hDerivative :
      HasDerivAt (fun upper => ∫ runUp in (0 : ℝ)..upper, kernel runUp)
        (kernel 0) 0 :=
    intervalIntegral.integral_hasDerivAt_right
      (hContinuous.intervalIntegrable 0 0)
      hContinuous.stronglyMeasurable.stronglyMeasurableAtFilter
      hContinuous.continuousAt
  have hSlope := hDerivative.tendsto_slope_zero
  have hRestricted := hSlope.mono_left
    (nhdsWithin_mono 0 (show Set.Ioi (0 : ℝ) ⊆ ({0} : Set ℝ)ᶜ by
      intro value hValue
      simpa only [Set.mem_compl_iff, Set.mem_singleton_iff] using
        ne_of_gt hValue))
  simpa [runUpAverage, runUpIntegral, kernel, div_eq_inv_mul,
    mul_comm] using hRestricted

/-- The centered pointwise maximum bounds every positive interval average. -/
theorem runUpAverage_le_center
    {contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand)
    (hOwn : 0 < ownInvestment) :
    runUpAverage contestedBand opponentBand temperature ownInvestment
        opponentInvestment ≤
      2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1 := by
  let center := 2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1
  have hIntegral :
      runUpIntegral contestedBand opponentBand temperature ownInvestment
          opponentInvestment ≤ ownInvestment * center := by
    unfold runUpIntegral
    have hMono := intervalIntegral.integral_mono_on
      (show (0 : ℝ) ≤ ownInvestment from le_of_lt hOwn)
      (runUpKernel_intervalIntegrable contestedBand opponentBand temperature
        opponentInvestment 0 ownInvestment)
      (Continuous.intervalIntegrable continuous_const 0 ownInvestment)
      (fun runUp _ =>
        marginalWindow_le_center hTemperature hBand)
    simpa [center] using hMono
  unfold runUpAverage
  apply (div_le_iff₀ hOwn).2
  dsimp [center] at hIntegral
  convert hIntegral using 1
  all_goals ring_nf

/-- Every genuinely positive run-up average lies strictly below the centered
pointwise value.  The strictness is proved inside the integral and does not
assume that an average maximizer exists. -/
theorem runUpAverage_lt_center
    {contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hOwn : 0 < ownInvestment) :
    runUpAverage contestedBand opponentBand temperature ownInvestment
        opponentInvestment <
      2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1 := by
  let center := 2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1
  let kernel := runUpKernel contestedBand opponentBand temperature
    opponentInvestment
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature
      opponentInvestment
  have hStrictPoint :
      ∃ point ∈ Set.Icc (0 : ℝ) ownInvestment, kernel point < center := by
    by_cases hLeft :
        (0 : ℝ) - opponentBand - opponentInvestment = -contestedBand / 2
    · refine ⟨ownInvestment, ⟨le_of_lt hOwn, le_rfl⟩, ?_⟩
      have hRight :
          ownInvestment - opponentBand - opponentInvestment ≠
            -contestedBand / 2 := by
        intro hEqual
        linarith
      dsimp [kernel, runUpKernel, feasibleMarginalWindow, center]
      exact marginalWindow_lt_center hTemperature hBand hRight
    · refine ⟨0, ⟨le_rfl, le_of_lt hOwn⟩, ?_⟩
      dsimp [kernel, runUpKernel, feasibleMarginalWindow, center]
      exact marginalWindow_lt_center hTemperature hBand hLeft
  have hIntegral :
      (∫ runUp in (0 : ℝ)..ownInvestment, kernel runUp) <
        ∫ _runUp in (0 : ℝ)..ownInvestment, center := by
    exact intervalIntegral.integral_lt_integral_of_continuousOn_of_le_of_exists_lt
      hOwn hContinuous.continuousOn continuous_const.continuousOn
      (fun runUp _ => by
        dsimp [kernel, runUpKernel, feasibleMarginalWindow, center]
        exact marginalWindow_le_center hTemperature (le_of_lt hBand))
      hStrictPoint
  simp only [intervalIntegral.integral_const, sub_zero, smul_eq_mul] at hIntegral
  unfold runUpAverage runUpIntegral
  apply (div_lt_iff₀ hOwn).2
  dsimp [kernel, center] at hIntegral
  convert hIntegral using 1
  all_goals ring_nf

theorem feasibleRunUpAverages_nonempty
    (contestedBand opponentBand temperature : ℝ) :
    (feasibleRunUpAverages contestedBand opponentBand temperature).Nonempty := by
  refine ⟨runUpAverage contestedBand opponentBand temperature 1 0, ?_⟩
  exact ⟨1, by norm_num, 0, le_rfl, rfl⟩

theorem feasibleRunUpAverages_bddAbove
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand) :
    BddAbove (feasibleRunUpAverages contestedBand opponentBand temperature) := by
  refine ⟨2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1, ?_⟩
  rintro value ⟨ownInvestment, hOwn, opponentInvestment, -, rfl⟩
  exact runUpAverage_le_center hTemperature hBand hOwn

theorem boundaryRunUpAverages_nonempty
    (contestedBand opponentBand temperature : ℝ) :
    (((fun ownInvestment =>
        runUpAverage contestedBand opponentBand temperature ownInvestment 0) ''
      Set.Ioi 0) : Set ℝ).Nonempty := by
  exact ⟨runUpAverage contestedBand opponentBand temperature 1 0,
    ⟨1, by norm_num, rfl⟩⟩

theorem boundaryRunUpAverages_bddAbove
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand) :
    BddAbove
      ((fun ownInvestment =>
        runUpAverage contestedBand opponentBand temperature ownInvestment 0) ''
          Set.Ioi 0) := by
  refine ⟨2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1, ?_⟩
  rintro value ⟨ownInvestment, hOwn, rfl⟩
  exact runUpAverage_le_center hTemperature hBand hOwn

theorem boundaryRunUpAverage_le_supremum
    {contestedBand opponentBand temperature ownInvestment : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand)
    (hOwn : 0 < ownInvestment) :
    runUpAverage contestedBand opponentBand temperature ownInvestment 0 ≤
      boundaryRunUpSupremum contestedBand opponentBand temperature := by
  unfold boundaryRunUpSupremum
  exact le_csSup
    (boundaryRunUpAverages_bddAbove
      (opponentBand := opponentBand) hTemperature hBand)
    ⟨ownInvestment, hOwn, rfl⟩

/-- The boundary value itself is below the supremum of positive prefix
averages, although it need not be attained by any such average. -/
theorem boundaryKernel_zero_le_supremum
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand) :
    runUpKernel contestedBand opponentBand temperature 0 0 ≤
      boundaryRunUpSupremum contestedBand opponentBand temperature := by
  let endpoint := runUpKernel contestedBand opponentBand temperature 0 0
  let maximum := boundaryRunUpSupremum contestedBand opponentBand temperature
  have hLimit :
      Filter.Tendsto
        (fun ownInvestment =>
          runUpAverage contestedBand opponentBand temperature ownInvestment 0)
        (nhdsWithin 0 (Set.Ioi 0)) (nhds endpoint) := by
    simpa [endpoint] using
      runUpAverage_tendsto_zero contestedBand opponentBand temperature 0
  have hBounded := boundaryRunUpAverages_bddAbove
    (opponentBand := opponentBand) hTemperature hBand
  by_contra hNotLe
  have hMaximumLt : maximum < endpoint := lt_of_not_ge hNotLe
  let midpoint := (maximum + endpoint) / 2
  have hMaximumMid : maximum < midpoint := by
    dsimp [midpoint]
    linarith
  have hMidEndpoint : midpoint < endpoint := by
    dsimp [midpoint]
    linarith
  have hEventuallyAbove :
      ∀ᶠ ownInvestment in nhdsWithin 0 (Set.Ioi 0),
        midpoint < runUpAverage contestedBand opponentBand temperature
          ownInvestment 0 :=
    hLimit.eventually (Ioi_mem_nhds hMidEndpoint)
  have hEventuallyBoth :
      ∀ᶠ ownInvestment in nhdsWithin 0 (Set.Ioi 0),
        0 < ownInvestment ∧
          midpoint < runUpAverage contestedBand opponentBand temperature
            ownInvestment 0 := by
    filter_upwards [self_mem_nhdsWithin, hEventuallyAbove] with
      ownInvestment hOwn hAbove
    exact ⟨hOwn, hAbove⟩
  obtain ⟨ownInvestment, hOwn, hAbove⟩ := hEventuallyBoth.exists
  have hMember :
      runUpAverage contestedBand opponentBand temperature ownInvestment 0 ∈
        ((fun length =>
          runUpAverage contestedBand opponentBand temperature length 0) ''
            Set.Ioi 0) :=
    ⟨ownInvestment, hOwn, rfl⟩
  have hLeMaximum :
      runUpAverage contestedBand opponentBand temperature ownInvestment 0 ≤
        maximum := by
    dsimp [maximum, boundaryRunUpSupremum]
    exact le_csSup hBounded hMember
  linarith

/-- Opponent investment translates the boundary interval to the left. -/
theorem runUpIntegral_eq_translated_boundary_integral
    (contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ) :
    runUpIntegral contestedBand opponentBand temperature ownInvestment
        opponentInvestment =
      ∫ translated in -opponentInvestment..ownInvestment - opponentInvestment,
        runUpKernel contestedBand opponentBand temperature 0 translated := by
  unfold runUpIntegral
  have hTranslate := intervalIntegral.integral_comp_sub_right
    (a := (0 : ℝ)) (b := ownInvestment)
    (runUpKernel contestedBand opponentBand temperature 0) opponentInvestment
  calc
    (∫ runUp in (0 : ℝ)..ownInvestment,
        runUpKernel contestedBand opponentBand temperature opponentInvestment
          runUp) =
        ∫ runUp in (0 : ℝ)..ownInvestment,
          runUpKernel contestedBand opponentBand temperature 0
            (runUp - opponentInvestment) := by
      apply intervalIntegral.integral_congr
      intro runUp _
      unfold runUpKernel feasibleMarginalWindow
      congr 1
      ring
    _ = ∫ translated in (0 : ℝ) - opponentInvestment..
          ownInvestment - opponentInvestment,
          runUpKernel contestedBand opponentBand temperature 0 translated :=
      hTranslate
    _ = ∫ translated in -opponentInvestment..
          ownInvestment - opponentInvestment,
          runUpKernel contestedBand opponentBand temperature 0 translated := by
      congr 1
      ring

/-- In the second branch, every point weakly to the left of the boundary
starting point has no larger kernel value. -/
theorem boundaryKernel_le_zero_of_lt_two_mul
    {contestedBand opponentBand temperature point : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hPoint : point ≤ 0) :
    runUpKernel contestedBand opponentBand temperature 0 point ≤
      runUpKernel contestedBand opponentBand temperature 0 0 := by
  have hMono :=
    (marginalWindow_strictMonoOn_left hTemperature hBand).monotoneOn
  unfold runUpKernel feasibleMarginalWindow
  apply hMono
  · change point - opponentBand - 0 ≤ -contestedBand / 2
    linarith
  · change (0 : ℝ) - opponentBand - 0 ≤ -contestedBand / 2
    linarith
  · linarith

/-- In the second branch, allowing an opponent investment cannot raise the
best average above the boundary (`a_j=0`) prefix supremum.  The proof splits
the translated interval at zero; its left part is bounded by the endpoint,
and its right part is one of the defining prefix averages. -/
theorem runUpAverage_le_boundarySupremum_of_lt_two_mul
    {contestedBand opponentBand temperature ownInvestment opponentInvestment : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand)
    (hOwn : 0 < ownInvestment)
    (hOpponent : 0 ≤ opponentInvestment) :
    runUpAverage contestedBand opponentBand temperature ownInvestment
        opponentInvestment ≤
      boundaryRunUpSupremum contestedBand opponentBand temperature := by
  let kernel := runUpKernel contestedBand opponentBand temperature 0
  let maximum := boundaryRunUpSupremum contestedBand opponentBand temperature
  have hContinuous : Continuous kernel :=
    runUpKernel_continuous contestedBand opponentBand temperature 0
  have hEndpointLe : kernel 0 ≤ maximum := by
    dsimp [kernel, maximum]
    exact boundaryKernel_zero_le_supremum hTemperature (le_of_lt hBand)
  have hLeftBound :
      ∀ {left right : ℝ}, left ≤ right → right ≤ 0 →
        (∫ point in left..right, kernel point) ≤ (right - left) * maximum := by
    intro left right hLeftRight hRight
    have hIntegral :
        (∫ point in left..right, kernel point) ≤
          ∫ _point in left..right, maximum := by
      exact intervalIntegral.integral_mono_on hLeftRight
        (hContinuous.intervalIntegrable left right)
        (continuous_const.intervalIntegrable left right)
        (fun point hPoint =>
          le_trans
            (boundaryKernel_le_zero_of_lt_two_mul hTemperature hBand hBranch
              (le_trans hPoint.2 hRight))
            hEndpointLe)
    simpa only [intervalIntegral.integral_const, smul_eq_mul] using hIntegral
  have hPrefixBound :
      ∀ {right : ℝ}, 0 < right →
        (∫ point in (0 : ℝ)..right, kernel point) ≤ right * maximum := by
    intro right hRight
    have hAverageLe := boundaryRunUpAverage_le_supremum
      (opponentBand := opponentBand) hTemperature (le_of_lt hBand) hRight
    have hIdentity :
        (∫ point in (0 : ℝ)..right, kernel point) =
          right * runUpAverage contestedBand opponentBand temperature right 0 := by
      unfold runUpAverage runUpIntegral
      dsimp [kernel]
      field_simp [ne_of_gt hRight]
    rw [hIdentity]
    exact mul_le_mul_of_nonneg_left hAverageLe (le_of_lt hRight)
  have hTranslated :
      runUpIntegral contestedBand opponentBand temperature ownInvestment
          opponentInvestment =
        ∫ point in -opponentInvestment..ownInvestment - opponentInvestment,
          kernel point := by
    simpa [kernel] using
      runUpIntegral_eq_translated_boundary_integral contestedBand opponentBand
        temperature ownInvestment opponentInvestment
  have hIntegralBound :
      runUpIntegral contestedBand opponentBand temperature ownInvestment
          opponentInvestment ≤ ownInvestment * maximum := by
    rw [hTranslated]
    by_cases hUpper : ownInvestment - opponentInvestment ≤ 0
    · have hBound := hLeftBound
        (show -opponentInvestment ≤ ownInvestment - opponentInvestment by linarith)
        hUpper
      convert hBound using 1
      all_goals ring
    · have hUpperPos : 0 < ownInvestment - opponentInvestment :=
        lt_of_not_ge hUpper
      have hLeft := hLeftBound (show -opponentInvestment ≤ 0 by linarith)
        le_rfl
      have hRight := hPrefixBound hUpperPos
      have hAdd := intervalIntegral.integral_add_adjacent_intervals
        (μ := MeasureTheory.volume)
        (hContinuous.intervalIntegrable (-opponentInvestment) 0)
        (hContinuous.intervalIntegrable 0
          (ownInvestment - opponentInvestment))
      rw [← hAdd]
      nlinarith
  unfold runUpAverage
  exact (div_le_iff₀ hOwn).2 (by
    simpa [maximum, mul_comm] using hIntegralBound)

/-- Consequently, the full feasible supremum equals the paper's second-branch
prefix supremum; no maximizer is assumed. -/
theorem feasibleRunUpSupremum_eq_boundarySupremum_of_lt_two_mul
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    feasibleRunUpSupremum contestedBand opponentBand temperature =
      boundaryRunUpSupremum contestedBand opponentBand temperature := by
  have hFeasibleNonempty := feasibleRunUpAverages_nonempty
    contestedBand opponentBand temperature
  have hFeasibleBounded := feasibleRunUpAverages_bddAbove
    (opponentBand := opponentBand) hTemperature (le_of_lt hBand)
  have hBoundaryNonempty := boundaryRunUpAverages_nonempty
    contestedBand opponentBand temperature
  apply le_antisymm
  · unfold feasibleRunUpSupremum
    apply csSup_le hFeasibleNonempty
    rintro value ⟨ownInvestment, hOwn, opponentInvestment, hOpponent, rfl⟩
    exact runUpAverage_le_boundarySupremum_of_lt_two_mul
      hTemperature hBand hBranch hOwn hOpponent
  · unfold boundaryRunUpSupremum
    apply csSup_le hBoundaryNonempty
    rintro value ⟨ownInvestment, hOwn, rfl⟩
    unfold feasibleRunUpSupremum
    exact le_csSup hFeasibleBounded
      ⟨ownInvestment, hOwn, 0, le_rfl, rfl⟩

theorem feasibleRunUpSupremum_eq_runUpMaximum_of_lt_two_mul
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : contestedBand < 2 * opponentBand) :
    feasibleRunUpSupremum contestedBand opponentBand temperature =
      runUpMaximum contestedBand opponentBand temperature := by
  rw [runUpMaximum, if_neg (not_le_of_gt hBranch)]
  exact feasibleRunUpSupremum_eq_boundarySupremum_of_lt_two_mul
    hTemperature hBand hBranch

/-- Exact order-theoretic certificate.  This equivalence does not require the
supremum to be attained. -/
theorem zeroRunUpWeaklyDominates_iff_supremum
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 ≤ contestedBand) :
    ZeroRunUpWeaklyDominates slotWeight contestedBand opponentBand cost
        temperature ↔
      slotWeight * feasibleRunUpSupremum contestedBand opponentBand temperature ≤
        cost := by
  have hNonempty := feasibleRunUpAverages_nonempty
    contestedBand opponentBand temperature
  have hBounded := feasibleRunUpAverages_bddAbove
    (opponentBand := opponentBand) hTemperature hBand
  constructor
  · intro hDominance
    have hSupLe :
        feasibleRunUpSupremum contestedBand opponentBand temperature ≤
          cost / slotWeight := by
      unfold feasibleRunUpSupremum
      apply csSup_le hNonempty
      rintro value ⟨ownInvestment, hOwn, opponentInvestment,
        hOpponent, rfl⟩
      have hGain := hDominance ownInvestment hOwn opponentInvestment hOpponent
      have hAverageIdentity :
          runUpIntegral contestedBand opponentBand temperature ownInvestment
                opponentInvestment =
            ownInvestment *
              runUpAverage contestedBand opponentBand temperature ownInvestment
                opponentInvestment := by
        unfold runUpAverage
        field_simp [ne_of_gt hOwn]
      rw [hAverageIdentity] at hGain
      have hScaled :
          slotWeight *
              runUpAverage contestedBand opponentBand temperature ownInvestment
                opponentInvestment ≤ cost := by
        nlinarith [hGain]
      exact (le_div_iff₀ hWeight).2 (by simpa [mul_comm] using hScaled)
    simpa [mul_comm] using (le_div_iff₀ hWeight).1 hSupLe
  · intro hSupremum ownInvestment hOwn opponentInvestment hOpponent
    have hMember :
        runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment ∈
          feasibleRunUpAverages contestedBand opponentBand temperature :=
      ⟨ownInvestment, hOwn, opponentInvestment, hOpponent, rfl⟩
    have hAverageLe :
        runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment ≤
          feasibleRunUpSupremum contestedBand opponentBand temperature := by
      unfold feasibleRunUpSupremum
      exact le_csSup hBounded hMember
    have hWeighted :
        slotWeight *
            runUpAverage contestedBand opponentBand temperature ownInvestment
              opponentInvestment ≤ cost :=
      le_trans (mul_le_mul_of_nonneg_left hAverageLe (le_of_lt hWeight))
        hSupremum
    have hAverageIdentity :
        runUpIntegral contestedBand opponentBand temperature ownInvestment
              opponentInvestment =
          ownInvestment *
            runUpAverage contestedBand opponentBand temperature ownInvestment
              opponentInvestment := by
      unfold runUpAverage
      field_simp [ne_of_gt hOwn]
    rw [hAverageIdentity]
    nlinarith

/-- In the first branch (`d_i ≥ 2 d_j`) the centered point is feasible as the
left endpoint of a run-up.  Positive averages approach the centered value as
their length tends to zero, so the feasible supremum equals that value. -/
theorem feasibleRunUpSupremum_eq_center_of_two_mul_le
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : 2 * opponentBand ≤ contestedBand) :
    feasibleRunUpSupremum contestedBand opponentBand temperature =
      2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1 := by
  let center := 2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1
  let opponentInvestment := contestedBand / 2 - opponentBand
  have hOpponent : 0 ≤ opponentInvestment := by
    dsimp [opponentInvestment]
    linarith
  have hAtCenter :
      runUpKernel contestedBand opponentBand temperature opponentInvestment 0 =
        center := by
    dsimp [runUpKernel, feasibleMarginalWindow, opponentInvestment, center]
    have hPosition :
        (0 : ℝ) - opponentBand - (contestedBand / 2 - opponentBand) =
          -contestedBand / 2 := by ring
    rw [hPosition]
    exact marginalWindow_center (ne_of_gt hTemperature)
  have hLimit :
      Filter.Tendsto
        (fun ownInvestment =>
          runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment)
        (nhdsWithin 0 (Set.Ioi 0)) (nhds center) := by
    simpa [hAtCenter] using
      runUpAverage_tendsto_zero contestedBand opponentBand temperature
        opponentInvestment
  have hNonempty := feasibleRunUpAverages_nonempty
    contestedBand opponentBand temperature
  have hBounded := feasibleRunUpAverages_bddAbove
    (opponentBand := opponentBand) hTemperature (le_of_lt hBand)
  apply le_antisymm
  · unfold feasibleRunUpSupremum
    apply csSup_le hNonempty
    rintro value ⟨ownInvestment, hOwn, opponent, -, rfl⟩
    exact runUpAverage_le_center hTemperature (le_of_lt hBand) hOwn
  · by_contra hNotLe
    have hSupLt :
        feasibleRunUpSupremum contestedBand opponentBand temperature < center :=
      lt_of_not_ge hNotLe
    let midpoint :=
      (feasibleRunUpSupremum contestedBand opponentBand temperature + center) / 2
    have hSupMid :
        feasibleRunUpSupremum contestedBand opponentBand temperature < midpoint := by
      dsimp [midpoint]
      linarith
    have hMidCenter : midpoint < center := by
      dsimp [midpoint]
      linarith
    have hEventuallyAbove :
        ∀ᶠ ownInvestment in nhdsWithin 0 (Set.Ioi 0),
          midpoint < runUpAverage contestedBand opponentBand temperature
            ownInvestment opponentInvestment :=
      hLimit.eventually (Ioi_mem_nhds hMidCenter)
    have hEventuallyBoth :
        ∀ᶠ ownInvestment in nhdsWithin 0 (Set.Ioi 0),
          0 < ownInvestment ∧
            midpoint < runUpAverage contestedBand opponentBand temperature
              ownInvestment opponentInvestment := by
      filter_upwards [self_mem_nhdsWithin, hEventuallyAbove] with
        ownInvestment hOwn hAbove
      exact ⟨hOwn, hAbove⟩
    obtain ⟨ownInvestment, hOwn, hAbove⟩ := hEventuallyBoth.exists
    have hMember :
        runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment ∈
          feasibleRunUpAverages contestedBand opponentBand temperature :=
      ⟨ownInvestment, hOwn, opponentInvestment, hOpponent, rfl⟩
    have hLeSup :
        runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment ≤
          feasibleRunUpSupremum contestedBand opponentBand temperature := by
      unfold feasibleRunUpSupremum
      exact le_csSup hBounded hMember
    linarith

theorem feasibleRunUpSupremum_eq_runUpMaximum_of_two_mul_le
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : 2 * opponentBand ≤ contestedBand) :
    feasibleRunUpSupremum contestedBand opponentBand temperature =
      runUpMaximum contestedBand opponentBand temperature := by
  rw [runUpMaximum, if_pos hBranch]
  exact feasibleRunUpSupremum_eq_center_of_two_mul_le
    hTemperature hBand hBranch

/-- First-branch equality is strict at every positive action: the supremum is
only approached as the interval shrinks to zero. -/
theorem zeroRunUpStrictlyDominates_of_center_le_cost
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hCertificate :
      slotWeight *
          (2 * Real.sigmoid (contestedBand / (2 * temperature)) - 1) ≤
        cost) :
    ZeroRunUpStrictlyDominates slotWeight contestedBand opponentBand cost
      temperature := by
  intro ownInvestment hOwn opponentInvestment _hOpponent
  have hAverage := runUpAverage_lt_center
    (opponentBand := opponentBand) (opponentInvestment := opponentInvestment)
    hTemperature hBand hOwn
  have hWeightedAverage :
      slotWeight *
          runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment < cost :=
    lt_of_lt_of_le
      (mul_lt_mul_of_pos_left hAverage hWeight) hCertificate
  have hAverageIdentity :
      runUpIntegral contestedBand opponentBand temperature ownInvestment
            opponentInvestment =
        ownInvestment *
          runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment := by
    unfold runUpAverage
    field_simp [ne_of_gt hOwn]
  rw [hAverageIdentity]
  nlinarith

/-- The paper's exact one-player dominance test in the first branch. -/
theorem zeroRunUpWeaklyDominates_iff_runUpMaximum_of_two_mul_le
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : 2 * opponentBand ≤ contestedBand) :
    ZeroRunUpWeaklyDominates slotWeight contestedBand opponentBand cost
        temperature ↔
      slotWeight * runUpMaximum contestedBand opponentBand temperature ≤ cost := by
  rw [zeroRunUpWeaklyDominates_iff_supremum hWeight hTemperature
    (le_of_lt hBand)]
  rw [feasibleRunUpSupremum_eq_runUpMaximum_of_two_mul_le
    hTemperature hBand hBranch]

/-- The two displayed branches exhaust the positive-band case. -/
theorem feasibleRunUpSupremum_eq_runUpMaximum
    {contestedBand opponentBand temperature : ℝ}
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand) :
    feasibleRunUpSupremum contestedBand opponentBand temperature =
      runUpMaximum contestedBand opponentBand temperature := by
  by_cases hBranch : 2 * opponentBand ≤ contestedBand
  · exact feasibleRunUpSupremum_eq_runUpMaximum_of_two_mul_le
      hTemperature hBand hBranch
  · exact feasibleRunUpSupremum_eq_runUpMaximum_of_lt_two_mul
      hTemperature hBand (lt_of_not_ge hBranch)

/-- Exact one-player dominance criterion for both branches of `M_i`. -/
theorem zeroRunUpWeaklyDominates_iff_runUpMaximum
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand) :
    ZeroRunUpWeaklyDominates slotWeight contestedBand opponentBand cost
        temperature ↔
      slotWeight * runUpMaximum contestedBand opponentBand temperature ≤ cost := by
  rw [zeroRunUpWeaklyDominates_iff_supremum hWeight hTemperature
    (le_of_lt hBand)]
  rw [feasibleRunUpSupremum_eq_runUpMaximum hTemperature hBand]

/-- A strict inequality against the true supremum makes every positive action
strictly dominated, without requiring a maximizing action. -/
theorem zeroRunUpStrictlyDominates_of_runUpMaximum_lt_cost
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hCertificate :
      slotWeight * runUpMaximum contestedBand opponentBand temperature < cost) :
    ZeroRunUpStrictlyDominates slotWeight contestedBand opponentBand cost
      temperature := by
  have hBounded := feasibleRunUpAverages_bddAbove
    (opponentBand := opponentBand) hTemperature (le_of_lt hBand)
  intro ownInvestment hOwn opponentInvestment hOpponent
  have hMember :
      runUpAverage contestedBand opponentBand temperature ownInvestment
          opponentInvestment ∈
        feasibleRunUpAverages contestedBand opponentBand temperature :=
    ⟨ownInvestment, hOwn, opponentInvestment, hOpponent, rfl⟩
  have hAverageLeSup :
      runUpAverage contestedBand opponentBand temperature ownInvestment
          opponentInvestment ≤
        feasibleRunUpSupremum contestedBand opponentBand temperature := by
    unfold feasibleRunUpSupremum
    exact le_csSup hBounded hMember
  rw [feasibleRunUpSupremum_eq_runUpMaximum hTemperature hBand] at hAverageLeSup
  have hWeightedAverage :
      slotWeight *
          runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment < cost :=
    lt_of_le_of_lt
      (mul_le_mul_of_nonneg_left hAverageLeSup (le_of_lt hWeight)) hCertificate
  have hAverageIdentity :
      runUpIntegral contestedBand opponentBand temperature ownInvestment
            opponentInvestment =
        ownInvestment *
          runUpAverage contestedBand opponentBand temperature ownInvestment
            opponentInvestment := by
    unfold runUpAverage
    field_simp [ne_of_gt hOwn]
  rw [hAverageIdentity]
  nlinarith

/-- Both players' zero actions weakly dominate their positive actions. -/
def BothPlayersZeroWeaklyDominate
    (slotWeight firstBand secondBand cost temperature : ℝ) : Prop :=
  ZeroRunUpWeaklyDominates slotWeight firstBand secondBand cost temperature ∧
    ZeroRunUpWeaklyDominates slotWeight secondBand firstBand cost temperature

/-- Exact two-player dominance test from part (i):
`w₁ max_i M_i ≤ κ`. -/
theorem bothPlayersZeroWeaklyDominate_iff
    {slotWeight firstBand secondBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hFirstBand : 0 < firstBand)
    (hSecondBand : 0 < secondBand) :
    BothPlayersZeroWeaklyDominate slotWeight firstBand secondBand cost
        temperature ↔
      slotWeight * twoPlayerRunUpMaximum firstBand secondBand temperature ≤
        cost := by
  rw [BothPlayersZeroWeaklyDominate,
    zeroRunUpWeaklyDominates_iff_runUpMaximum hWeight hTemperature hFirstBand,
    zeroRunUpWeaklyDominates_iff_runUpMaximum hWeight hTemperature hSecondBand]
  constructor
  · rintro ⟨hFirst, hSecond⟩
    unfold twoPlayerRunUpMaximum
    rw [mul_max_of_nonneg _ _ (le_of_lt hWeight)]
    exact max_le hFirst hSecond
  · intro hBoth
    constructor
    · exact le_trans
        (mul_le_mul_of_nonneg_left (le_max_left _ _) (le_of_lt hWeight)) hBoth
    · exact le_trans
        (mul_le_mul_of_nonneg_left (le_max_right _ _) (le_of_lt hWeight)) hBoth

/-- Strict version of the two-player test. -/
theorem bothPlayersZeroStrictlyDominate_of_lt
    {slotWeight firstBand secondBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hFirstBand : 0 < firstBand)
    (hSecondBand : 0 < secondBand)
    (hCertificate :
      slotWeight * twoPlayerRunUpMaximum firstBand secondBand temperature <
        cost) :
    ZeroRunUpStrictlyDominates slotWeight firstBand secondBand cost temperature ∧
      ZeroRunUpStrictlyDominates slotWeight secondBand firstBand cost
        temperature := by
  constructor
  · apply zeroRunUpStrictlyDominates_of_runUpMaximum_lt_cost
      hWeight hTemperature hFirstBand
    exact lt_of_le_of_lt
      (mul_le_mul_of_nonneg_left (le_max_left _ _) (le_of_lt hWeight))
      hCertificate
  · apply zeroRunUpStrictlyDominates_of_runUpMaximum_lt_cost
      hWeight hTemperature hSecondBand
    exact lt_of_le_of_lt
      (mul_le_mul_of_nonneg_left (le_max_right _ _) (le_of_lt hWeight))
      hCertificate

/-- On the centered first branch, the run-up test reduces exactly to the
closed-form `τ°` certificate from `ExactThreshold`. -/
theorem firstBranch_runUpMaximum_le_cost_iff_tauCircle
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hCost : 0 < cost) (hCostWeight : cost < slotWeight)
    (hTemperature : 0 < temperature)
    (hBranch : 2 * opponentBand ≤ contestedBand) :
    slotWeight * runUpMaximum contestedBand opponentBand temperature ≤ cost ↔
      tauCircle contestedBand slotWeight cost ≤ temperature := by
  rw [runUpMaximum, if_pos hBranch]
  change pointwiseMarginalValue slotWeight contestedBand temperature ≤ cost ↔ _
  exact pointwiseMarginalValue_le_cost_iff hWeight hCost hCostWeight hTemperature

/-- Equality in the first branch still gives strict dominance because its
supremum is reached only in the zero-length limit. -/
theorem firstBranch_equality_gives_strict_dominance
    {slotWeight contestedBand opponentBand cost temperature : ℝ}
    (hWeight : 0 < slotWeight)
    (hTemperature : 0 < temperature)
    (hBand : 0 < contestedBand)
    (hBranch : 2 * opponentBand ≤ contestedBand)
    (hEquality :
      slotWeight * runUpMaximum contestedBand opponentBand temperature = cost) :
    ZeroRunUpStrictlyDominates slotWeight contestedBand opponentBand cost
      temperature := by
  apply zeroRunUpStrictlyDominates_of_center_le_cost
    hWeight hTemperature hBand
  rw [runUpMaximum, if_pos hBranch] at hEquality
  exact le_of_eq hEquality

/-- By contrast, whenever the second-branch supremum is attained, equality of
cost and `w₁ M_i` produces an actual tying positive deviation. -/
theorem attainedBoundaryMaximum_ties_at_equality
    {slotWeight contestedBand opponentBand cost temperature optimalLength : ℝ}
    (hOptimal : 0 < optimalLength)
    (hAttains :
      boundaryRunUpSupremum contestedBand opponentBand temperature =
        runUpAverage contestedBand opponentBand temperature optimalLength 0)
    (hEquality :
      slotWeight * boundaryRunUpSupremum contestedBand opponentBand temperature =
        cost) :
    slotWeight *
        runUpIntegral contestedBand opponentBand temperature optimalLength 0 =
      cost * optimalLength := by
  have hIntegral :
      runUpIntegral contestedBand opponentBand temperature optimalLength 0 =
        optimalLength *
          runUpAverage contestedBand opponentBand temperature optimalLength 0 := by
    unfold runUpAverage
    field_simp [ne_of_gt hOptimal]
  rw [hIntegral, ← hAttains]
  nlinarith

end

end SmoothingCliff.Racing
